### register user
POST localhost:9090/auth/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "fullName": "tester_fullname",
  "password": "tester",
  "username": "test-er"

}

### user login
POST localhost:9090/auth/login
Content-Type: application/json

{
  "username": "test-er",
  "password": "tester"
}